### ISSUE TITLE
Symbol component

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/pickify-frontend#214]
## Symbol Component:

**A component should display single letter inside every TextInput component and every post option view**

![Screenshot from 2021-06-18 03-36-10](https://user-images.githubusercontent.com/52901348/122492697-85412980-cfe6-11eb-9fd3-8dadf0478686.png)
![Screenshot from 2021-06-18 03-36-30](https://user-images.githubusercontent.com/52901348/122492699-85d9c000-cfe6-11eb-9921-91c939fb7a5d.png)
![Screenshot from 2021-06-18 03-36-38](https://user-images.githubusercontent.com/52901348/122492700-86725680-cfe6-11eb-8900-ed7fd01a2c6b.png)

### tasks

- [ ] Component matches the UI 
- [ ] typescript declaration
- [ ] add Storybook
- [ ] add snap shot tests
- [ ] add the required variants
- [ ] add a function that generates the letters and separate it in the logic folder with its tests

#### what is the correct behavior when the user add more than 28 options and goes beyond the last letter **z** ?!!
