### ISSUE TITLE
optimize images size before submitting it to the backend

### ISSUE THREAD

**Issue by ahmedkhitaby** [m3ntorship/pickify-frontend#284]
### Story
- [ ] Each image submitted with its full size which is not good for the time the user should wait after submitting the post until he could leave the page or refresh it, so the request is considered to be completed.

### Prerequisites
- [ ] It would be great if we reduce the image size for example from 5MB to 1MB or less.

### Tasks
- [ ] Optimize and reduce images size before submitting it to the backend
